### ISSUE TITLE
参与人数到一定数量时，luckynumber趋于固定的范围

### ISSUE THREAD

**Issue by 18916204759** [jysperm/rollup#2]
基于代码里面的算法，当参与人数超过一定数量后，产生的luckynumber趋于25xxxxxxxx，基本算不上随机了。

**Comment by jysperm** [comment]
感谢关注，luckyNumber 是来自于一次散列的（而不是平均数），散列函数有着很强的随机性，所以理论上并不会受到参与人数的影响。你是有试验过么，还是从理论上推断的？

**Comment by 18916204759** [comment]
测试的结果，parseInt(luckyHash.slice(-8), 16)代码里面只是取了最大的SecretNumber的后8位

**Comment by jysperm** [comment]
确实 ... 是我漏写了 md5：

```diff
- const luckyHash = _.sortBy(secretNumbers).join();
+ const luckyHash = md5(_.sortBy(secretNumbers).join());
```

**Comment by jysperm** [comment]
已在主分支上修复
